### ISSUE TITLE
RAM size in EnvisionDemo18 linker/loader file

### ISSUE THREAD

**Issue by jancumps** [miniwinwm/RenesasEnvisionGCC#1]
In the loader file for demo 18:
https://github.com/miniwinwm/RenesasEnvisionGCC/blob/master/EnvisionDemo18/generate/linker_script.ld
RAM is set to 655360. But this refers to the block betwen addres 0x0000 0000 and 0x0003 FFFF.
That's 256 kB. Would this not be 262144‬ ?

From:
```
MEMORY
{
	RAM : ORIGIN = 0x0, LENGTH = 655360
```

To:
```
MEMORY
{
	RAM : ORIGIN = 0x0, LENGTH = 262144‬
```

**Comment by jancumps** [comment]
Pull request: #2

**Comment by miniwinwm** [comment]
Thanks, now merged. I'm not using RX processors at the moment which is why this took time to get round to. Sorry for the delay.
